/** @type {import('tailwindcss').Config} */

const plugin = require("tailwindcss/plugin");

module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
"font-open-sans-light",
"uppercase",
"text-3xl",
"text-gray-600",
"leading-8",
"text-main",
"text-xl",
"mt-8",
"md:mt-3",
"font-open-sans-regular",
"text-md",
"leading-normal",
"text-black",
"mt-2",
"mt-3",
"pr-12",
"break-words",
"mt-4",
"md:mt-0",
"w-40",
"text-sm",
"text-center",
"underline",
"leading-tight",
"tracking-tight",
"font-open-sans-semibold",
"text-xs",
"",
"md:text-lg",
"tracking-wide",
"mb-1",
"md:mb-0",
"hover:underline",
"text-4xl",
"md:text-6xl",
"2xl:text-7xl",
"text-alert",
"md:text-3xl",
"md:leading-8",
"lg:mt-20",
"md:pr-20",
"leading-6",
"mb-4",
"md:px-8",
"text-lg",
"text-gray-500",
"leading-5",
"my-2",
"lg:text-2xl",
"xl:text-3xl",
"tracking-wider",
"md:font-open-sans-light",
"p-2",
"md:w-48",
"lg:w-36",
"xl:w-44",
"md:aspect-square",
"flex",
"items-center",
"md:rounded-full",
"md:bg-white",
"md:text-black",
"lg:text-xs",
"xl:text-base",
"mb-8"],
  theme: {
    extend: {
      fontFamily: {
        "open-sans-regular": ["OpenSansRegular"],
        "open-sans-semibold": ["OpenSansSemiBold"],
        "open-sans-bold": ["OpenSansBold"],
        "open-sans-light-italic": ["OpenSansLightItalic"],
        "open-sans-light": ["OpenSansLight"],
      },
      height: {
        banner: "45.9375rem",
        slider: "36rem",
        grape: "21.87rem",
        citro: "25rem",
      },
      minHeight: {
        slider: "36rem",
      },
      width: {
        grape: "21.87rem",
        citro: "25rem",
      },
      backgroundImage: {
        "banner-image": "url('/images/banner.webp')",
        "about-background": "url('/images/about-background-v2.webp')",
        "banner-background": "url('/images/banner-background.webp')",
        "footer-background": "url('/images/footer-background.gif')",
        "immunity-background": "url('/images/green.webp')",
        wave: "url('/images/wave.svg')",
        "wave-bold": "url('/images/wave-bold.svg')",
      },
      colors: {
        main: "#ef462c",
        "footer-start": "#97d794",
        "footer-end": "#7ec87b",
        "text-semi-transparent": "rgba(255, 255, 255, 0.27)",
        alert: "#d5d5d6",
      },
      gridTemplateRows: {
        "about-rows": "auto auto auto",
        "immunity-rows": "auto auto auto",
        0: "0fr",
        opened: "1fr",
      },
      gridTemplateColumns: {
        "about-cols": "1.3fr 0.8fr 1.3fr",
        "immunity-cols": "auto auto auto",
      },
      textShadow: {
        sm: "2px 2px 15px var(--tw-shadow-color)",
        default: "0 2px 4px var(--tw-shadow-color)",
        lg: "0 8px 16px var(--tw-shadow-color)",
      },
    },
  },
  plugins: [
    plugin(function ({ matchUtilities, theme }) {
      matchUtilities(
        {
          "text-shadow": (value) => ({
            textShadow: value,
          }),
        },
        { values: theme("textShadow") }
      );
    }),
  ],
};
